esphome:
  name: bk7231n-bureau-led
  friendly_name: BK7231N Burreau Led

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret bk7231n_bureau_led_api_key

ota:
  platform: esphome
  password: !secret bk7231n_bureau_led_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "bk7231n-bureau-led"
    password: "vPvH5kanxjKE"

web_server:

captive_portal:

light:
  - platform: neopixelbus
    type: RGB
    variant: WS2812X
    pin: P16
    num_leds: 60
    name: "Bandeau LED Bureau"