esphome:
  name: esphome-32-temperature
  friendly_name: ESPHome 32 Température

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_32_temperature_api_key

ota:
  platform: esphome
  password: !secret esphome_32_temperature_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-32-Temperature"
    password: "2hJpZKsbWwXX"

captive_portal:
    
esp32_ble_tracker:
sensor:
  #Salon
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:49:FD:59"
    temperature:
      name: "temperature_salon"
    humidity:
      name: "humidity_salon"
    battery_level:
      name: "battery-level-ATC-salon"
    battery_voltage:
      name: "battery-voltage-ATC-salon"
    signal_strength:
      name: "signal-ATC-salon"
  #Bedroom
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:2D:32:8D"
    temperature:
      name: "temperature_bedroom"
    humidity:
      name: "humidity_bedroom"
    battery_level:
      name: "battery-level-ATC-bedroom"
    battery_voltage:
      name: "battery-voltage-ATC-bedroom"
    signal_strength:
      name: "signal-ATC-bedroom"
  #Bedroom 2
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:36:80:5E"
    temperature:
      name: "temperature_bedroom2"
    humidity:
      name: "humidity_bedroom2"
    battery_level:
      name: "battery-level-ATC-bedroom2"
    battery_voltage:
      name: "battery-voltage-ATC-bedroom2"
    signal_strength:
      name: "signal-ATC-bedroom2"
  #Office
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:7C:DB:B0"
    temperature:
      name: "temperature_office"
    humidity:
      name: "humidity_office"
    battery_level:
      name: "battery-level-ATC-office"
    battery_voltage:
      name: "battery-voltage-ATC-office"
    signal_strength:
      name: "signal-ATC-office"